# Mixed Effect Boosting

## Settings

```{r}
#loaded librarires
library(dplyr)
library(car) #to apply transformations
library(MVN) #to perform multivariate gaussianity check

library(GGally) #for ggcorr
library(ggplot2)

library(randomForest) #bagging
library(gbm) #boosting

library(caret) #tuner for ML algorithms

library(glmnet)
library(lme4)
library(nlmeU) ## --> for the dataset
library(nlme)  ## --> for models implementation

library(corrplot)
library(lattice)
library(plot.matrix)

library(insight)
```

```{r}
set.seed(42)
#DIRECTORIES
root_proj_dir = "../../"
dataset_dir = paste(root_proj_dir,"/data/pisa_scores_final.csv",sep="")
include_dir = paste(root_proj_dir,"/src/include/Utilities.R",sep="")
#INCLUDING UTILITIES
source(include_dir)
#IMPORTING THE DATASET
pisa_data <- read.csv(file=dataset_dir)
```

```{r}
#some adjustments on the data
pisa_data$CNT <- as.factor(pisa_data$CNT)
pisa_data$SCHLTYPE <- as.factor(pisa_data$SCHLTYPE)

#standardizing
transformed_data <- as.data.frame(scale(select_if(pisa_data,is.numeric)))
transformed_data$CNT <- pisa_data$CNT #adding CNT column
transformed_data$SCHLTYPE <- pisa_data$SCHLTYPE #adding SCHLTYPE column

pisa_data <- transformed_data
rm(transformed_data)

pisa_data$X <- NULL
#check on data 
boxplot(select_if(pisa_data,is.numeric),las=2)


#shuffle data
shuffled_rows_index <- sample(1:nrow(pisa_data))
pisa_data <- pisa_data[shuffled_rows_index,]
```

# Fitting the Boosting model

## Fixed effect

Constructing the formula object

```{r}
#regressors
regressors <- names(pisa_data)
to_discard <- c("CNT", "Social.well.being", "Psychological.well.being", "SCHLTYPE")
regressors <- regressors[!regressors %in% to_discard]

#formula object
formula_str <- paste("Social.well.being", paste(regressors, collapse = "+"), sep ="~")
```

Tuning

```{r}
# training settings
gbm_control <- trainControl(method="cv", 
                            number=5,
                            verboseIter = TRUE)

# setting the grid
gbm_grid <- expand.grid(n.trees = c(5000,10000),
                        interaction.depth = c(3, 6),
                        shrinkage = c(0.01, 0.05),
                        n.minobsinnode = 10)
                                        
# actual training
gbm_training <- train(as.formula(formula_str), 
                    data=pisa_data, 
                    method="gbm", 
                    metric = "Rsquared", 
                    tuneGrid = gbm_grid, 
                    trControl = gbm_control,
                    verbose = FALSE)

#to see what's inside the method used to fit
getModelInfo(model = "gbm", regex = FALSE)

# print the summary
gbm_training
```

## Mixed effect

```{r}

```
