---
title: "PISA dataset na exploration"
output: 
editor_options: 
  chunk_output_type: inline
---

# Map for variable meaning
```{r}
## Quick get meaning of a variable
what_is <- new.env(hash = TRUE, parent = emptyenv(), size = NA)
## insert into hash table
what_is[["MMINS"]] = "Learning time (minutes per week) - <Mathematics>" 
what_is[["LMINS"]] = "Learning time (minutes per week) - <test language>" 
what_is[["SMINS"]] = "Learning time (minutes per week) - <science>" 
what_is[["TMINS"]] = "Learning time (minutes per week) - in total" 
what_is[["FCFMLRTY"]] = "Familiarity with concepts of finance (Sum)" 
what_is[["SCCHANGE"]] = "Number of school changes" 
what_is[["CHANGE"]] = "Number of changes in educational biography (Sum)" 
what_is[["STUBMI"]] = "Body mass index of student" 
what_is[["ESCS"]] = "Index of economic social and cultural status" 
what_is[["UNDREM"]] = "Meta-cognition: understanding and remembering" 
what_is[["METASUM"]] = "Meta-cognition: summarising" 
what_is[["METASPAM"]] = "Meta-cognition: assess credibility" 
what_is[["ICTHOME"]] = "ICT available at home" 
what_is[["ICTSCH"]] = "ICT available at school" 
what_is[["HOMEPOS"]] = "Home possessions (WLE)" 
what_is[["CULTPOSS"]] = "Cultural possessions at home (WLE)" 
what_is[["HEDRES"]] = "Home educational resources (WLE)" 
what_is[["WEALTH"]] = "Family wealth (WLE)" 
what_is[["ICTRES"]] = "ICT resources (WLE)" 
what_is[["DISCLIMA"]] = "Disciplinary climate in test language lessons (WLE)" 
what_is[["TEACHSUP"]] = "Teacher support in test language lessons (WLE)" 
what_is[["DIRINS"]] = "Teacher-directed instruction (WLE)" 
what_is[["PERFEED"]] = "Perceived feedback (WLE)" 
what_is[["EMOSUPS"]] = "Parents' emotional support perceived by student (WLE)" 
what_is[["STIMREAD"]] = "Teacher's stimulation of reading engagement perceived by student (WLE)" 
what_is[["ADAPTIVITY"]] = "Adaptation of instruction (WLE)" 
what_is[["TEACHINT"]] = "Perceived teacher's interest (WLE)" 
what_is[["JOYREAD"]] = "Joy/Like reading (WLE)" 
what_is[["HISEI"]] = "Index highest parental occupational status" 
what_is[["SCREADCOMP"]] = "Self-concept of reading: Perception of competence (WLE)" 
what_is[["SCREADDIFF"]] = "Self-concept of reading: Perception of difficulty (WLE)" 
what_is[["PISADIFF"]] = "Perception of difficulty of the PISA test (WLE)" 
what_is[["PERCOMP"]] = "Perception of competitiveness at school (WLE)" 
what_is[["PERCOOP"]] = "Perception of cooperation at school (WLE)" 
what_is[["ATTLNACT"]] = "Attitude towards school: learning activities (WLE)" 
what_is[["COMPETE"]] = "Competitiveness (WLE)" 
what_is[["BFMJ2"]] =	"ISEI of father"
what_is[["BMMJ1"]] =	"ISEI of mother"
what_is[["HISCED"]] =	"Highest Education of parents (ISCED)"
what_is[["HISEI"]] =	"Index highest parental occupational status"
what_is[["WORKMAST"]] = "Work mastery (WLE)" 
what_is[["GFOFAIL"]] = "General fear of failure (WLE)" 
what_is[["EUDMO"]] = "Eudaemonia: meaning in life (WLE)" 
what_is[["SWBP"]] = "Subjective well-being: Positive affect (WLE)" 
what_is[["RESILIENCE"]] = "Resilience (WLE)" 
what_is[["MASTGOAL"]] = "Mastery goal orientation (WLE)" 
what_is[["GCSELFEFF"]] = "Self-efficacy regarding global issues (WLE)" 
what_is[["GCAWARE"]] = "Student's awareness of global issues (WLE)" 
what_is[["ATTIMM"]] = "Student's attitudes towards immigrants (WLE)" 
what_is[["INTCULT"]] = "Student's interest in learning about other cultures (WLE)" 
what_is[["PERSPECT"]] = "Perspective-taking (WLE)" 
what_is[["COGFLEX"]] = "Cognitive flexibility/adaptability (WLE)" 
what_is[["RESPECT"]] = "Respect for people from other cultures (WLE)" 
what_is[["AWACOM"]] = "Awareness of intercultural communication (WLE)" 
what_is[["GLOBMIND"]] = "Global-mindedness (WLE)" 
what_is[["DISCRIM"]] = "Discriminating school climate (WLE)" 
what_is[["BELONG"]] = "Subjective well-being: Sense of belonging to school (WLE)" 
what_is[["BEINGBULLIED"]] = "Student's experience of being bullied (WLE)" 
what_is[["ENTUSE"]] = "ICT use outside of school (leisure) (WLE)" 
what_is[["HOMESCH"]] = "Use of ICT outside of school (for school work activities) (WLE)" 
what_is[["USESCH"]] = "Use of ICT at school in general (WLE)" 
what_is[["INTICT"]] = "Interest in ICT (WLE)" 
what_is[["COMPICT"]] = "Perceived ICT competence (WLE)" 
what_is[["AUTICT"]] = "Perceived autonomy related to ICT use (WLE)" 
what_is[["SOIAICT"]] = "ICT as a topic in social interaction (WLE)" 
what_is[["ICTCLASS"]] = "Subject-related ICT use during lessons (WLE)" 
what_is[["ICTOUTSIDE"]] = "Subject-related ICT use outside of lessons (WLE)" 
what_is[["INFOCAR"]] = "Information about careers (WLE)" 
what_is[["INFOJOB1"]] = "Information about the labour market provided by the school (WLE)" 
what_is[["INFOJOB2"]] = "Information about the labour market provided outside of school (WLE)" 
what_is[["FLCONFIN"]] = "Confidence about financial matters (WLE)" 
what_is[["FLCONICT"]] = "Confidence about financial matters using digital devices (WLE)" 
what_is[["FLSCHOOL"]] = "Financial education in school lessons (WLE)" 
what_is[["FLFAMILY"]] = "Parental involvement in matters of Financial Literacy (WLE)" 
what_is[["CURSUPP"]] = "Current parental support for learning at home (WLE)" 
what_is[["EMOSUPP"]] = "Parents' emotional support (WLE)" 
what_is[["PQSCHOOL"]] = "Parents' perceived school quality (WLE)" 
what_is[["PASCHPOL"]] = "School policies for parental involvement (WLE)" 
what_is[["PRESUPP"]] = "Previous parental support for learning at home (WLE)" 
what_is[["JOYREADP"]] = "Parents enjoyment of reading (WLE)" 
what_is[["ATTIMMP"]] = "Parents' attitudes towards immigrants (WLE)" 
what_is[["INTCULTP"]] = "Parents' interest in learning about other cultures (WLE)" 
what_is[["GCAWAREP"]] = "Parents' awareness of global issues (WLE)" 
what_is[["BODYIMA"]] = "Body image (WLE)" 
what_is[["SOCONPA"]] = "Social Connections: Parents (WLE)"

#usage
what_is[["PISADIFF"]]
what_is[["SCREADCOMP"]]
what_is[["ATTLNACT"]]
what_is[["COGFLEX"]]
```


# Setup
```{r}
#variabili finite nel dataset
tec=c("ICTCLASS","ICTHOME","ICTOUTSIDE","ICTRES","AUTICT","COMPICT","INTICT","ENTUSE","HOMESCH","USESCH")
psi=c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","GFOFAIL","SWBP","RESILIENCE","BELONG","BEINGBULLIED","PERFEED")
clt=c("JOYREAD","CULTPOSS","HEDRES","SCREADCOMP","LMINS","MMINS")
fam=c("WEALTH","ESCS","HOMEPOS","BFMJ2","BMMJ1","HISCED","HISEI")
tch=c("TEACHINT","TEACHSUP","STIMREAD")
sch=c("PERCOMP","PERCOOP","ICTSCH","RATCMP1") #,"RATCMP2")

df=read.csv("../../data/pisa-woNA_school_final.csv")
colnames(df)
head(df)
df=df[,-c(1)] #remove  X (index) column

sort(colnames(df[,-c(1,2,3)])) == sort(c(tec,psi,clt,fam,tch,sch))
#c'è tutto ora
#variabili nuove
colnames(df)[c(1,2,3)]

head(df$schID)
length(unique(df$schID))
dim(df) #è davvero un id allora

head(df$gender_prop) #??

df_tec = df[,colnames(df) %in% tec]
df_psi = df[,colnames(df) %in% psi]
df_clt = df[,colnames(df) %in% clt]
df_fam = df[,colnames(df) %in% fam]
df_tch = df[,colnames(df) %in% tch]
df_sch = df[,colnames(df) %in% sch]
```

# States
```{r}
states = unique(df$CNT)
len = length(unique(df$CNT))
hcl.pals()
col.ramp = hcl.colors(len, palette = "viridis")
```

## SWBP for states
```{r}
boxplot(df$SWBP ~ df$CNT,las=2, col=col.ramp, main="SWBP for states, by-school dataset")
```

## SWBP for schools in states
```{r}
unique(df$CNT)

for(state in states){
	plot(df$SWB[which(df$CNT==state)] ~ df$schID[which(df$CNT==state)], main=paste("SWBP for the schools in",state))
}
```

## Comparison of the means in states
```{r}
psi=c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","GFOFAIL","SWBP","RESILIENCE","BELONG","BEINGBULLIED","PERFEED")
for (val in psi){
	print(what_is[[val]])
}
# pos_val =c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","SWBP","RESILIENCE","BELONG","PERFEED")
# neg_val =c("GFOFAIL","BEINGBULLIED")

# plot(df$SWB[which(df$CNT==state)] ~ df$schID[which(df$CNT==state)], main=paste("SWBP for the schools in",state))
vec_medie = rep(0,length(unique(states)))
it=0
for(state in states){
	vec_medie[it] = mean(df$SWB[which(df$CNT==state)])
	it=it+1
}
length(vec_medie)
length(states)
delta=1/20
plot(1:length(unique(states)),vec_medie, main="SWBP mean in states, by-school dataset",
	 ylim=c(min(vec_medie),max(vec_medie)+delta), col=col.ramp, pch=19)
x=1
for(state in states){
	text(x,vec_medie[x]+delta,state)
	x=x+1
}
states
```



