---
title: "PISA dataset na exploration"
output: 
editor_options: 
  chunk_output_type: inline
---

# Map for variable meaning
```{r}
source("../include/Utilities.R")
```


# Setup
```{r}
#variabili finite nel dataset
tec=c("ICTCLASS","ICTHOME","ICTOUTSIDE","ICTRES","AUTICT","COMPICT","INTICT","ENTUSE","HOMESCH","USESCH")
psi=c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","GFOFAIL","SWBP","RESILIENCE","BELONG","BEINGBULLIED","PERFEED")
clt=c("JOYREAD","CULTPOSS","HEDRES","SCREADCOMP","LMINS","MMINS","STUBEHA")
fam=c("WEALTH","ESCS","HOMEPOS","BFMJ2","BMMJ1","HISCED","HISEI")
tch=c("TEACHINT","TEACHSUP","STIMREAD","PROAT5AB","PROAT5AM","PROAT6","TEACHBEHA")
sch=c("PERCOMP","PERCOOP","ICTSCH","RATCMP1","STRATIO","SCHSIZE","CLSIZE","CREACTIV","EDUSHORT","STAFFSHORT")

df=read.csv("../../data/pisa_wPV_grouped_bysch.csv")
colnames(df)
library(dplyr)
df=df[,-c(1,2,3)] #remove X (index) column
df <- df %>% select(-starts_with("PV")) #excluding target variables 
colnames(df)

sort(colnames(df[,-c(52)]))==sort(c(tec,psi,clt,fam,tch,sch))
#c'è tutto ora

df_tec = df[,colnames(df) %in% tec]
df_psi = df[,colnames(df) %in% psi]
df_clt = df[,colnames(df) %in% clt]
df_fam = df[,colnames(df) %in% fam]
df_tch = df[,colnames(df) %in% tch]
df_sch = df[,colnames(df) %in% sch]
```

# States
```{r}
states = unique(df$CNT)
len = length(unique(df$CNT))
hcl.pals()
col.ramp = hcl.colors(len, palette = "viridis")

boxplot(df$SWBP ~ df$CNT,las=2, col=col.ramp)
```

```{r}
categories = c("tec","psi","clt","fam","tch","sch")
# for (df_curr in c(df_tec,df_psi,df_clt,df_fam,df_tch,df_sch)) {
```

# PCA on categories
## tec
```{r}
cat_curr_vec = tec
cat_curr_name = "tec"
df_curr = df_tec

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
want_to_scale=1

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# PC1 seems to stress more on the actual proficiency (efficienza?) of the student in tecnology,
# almost discarding the amount of availability he/she actually has (in fact ictclass and
# ictres are lower than the others). Tipo quanto sono bravo malgrado le circostanze

# PC2 semms to stress invece il mero uso della tecnologia (a scuola, casa, per
# school work and at school in general), contro il suo vero interesse per la questione
# (la sua competence, interest, autonomy)
```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}


```

## psi
```{r}
cat_curr_vec = psi
cat_curr_name = "psi"
df_curr = df_psi

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
want_to_scale=1

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# PC1 sembra fare la somma dei contributi positivi contro quelli negativi: cioè tutti
# sommati tranne gfofail e beingbullied. Quindi PC1 alta vuol dire starm meglio

# PC2 sembra fare un contrasto tra valori più materiali (wealth, homeposs) e altri più morali (teachsup,
# emosup, eudmo, reslience)
```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}

```



## clt
```{r}
cat_curr_vec = clt
cat_curr_name = "clt"
df_curr = df_clt

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
# df_new = df_curr
# df_new$LMINS = log(df_curr$LMINS+1)
# df_new$MMINS = log(df_curr$MMINS+1)
# boxplot(df_new)
# df_curr = df_new
# non cambia molto la pca
want_to_scale=1

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# PC1 sembra concentrarsi più sulla cultura in senso lato, mentre PC2 sul contrasto
# tra questo e lo studio effettivo
# alta PC1 -> lo studente ha disponibilità (gli piace molto, ha libri a casa, ecc)
# alta PC2 -> lo studente ha molta cultura disponibile ma non studia molto
# bassa PC2 -> lo studente studia molto

```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}


```


## fam
```{r}
cat_curr_vec = fam
cat_curr_name = "fam"
df_curr = df_fam

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
want_to_scale=1

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# PC1 fa una media di tutto, quindi PC1 alta -> tutto va bene in famiglia,
# almeno a livello economico
# PC2 fa contrasto tra possessioni materiali (wealth, homeposs) e culturali
# Quindi PC2 bassa (intesa naturalmente anche come <0) -> maggiore peso culturale
# PC2 alta -> la famiglia è più facoltosa nella realtà  
```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}


```



## tch
```{r}
cat_curr_vec = tch
cat_curr_name = "tch"
df_curr = df_tch

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
want_to_scale=0

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation tch
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# PC1 fa una media dei vari contributi
# PC2 fa contrasto tra eh, queste variabili non hanno una spiegazione molto chiara
# Forse PC2 alta -> il prof trasmette molta passione (alta intereset e stimulation)
# PC2 bassa (naturalmente anche <0) -> il prof dà più supporto pratico che trasfusionale
```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}

```




## sch
```{r}
cat_curr_vec = sch
cat_curr_name = "sch"
df_curr = df_sch

###############################################################################
colnames(df_curr)
boxplot(df_curr, las=2)
want_to_scale=1

if(want_to_scale==1){
  df2 = scale(df_curr[,])
} else{
  df2 = df_curr
}
df2 = data.frame(df2)
df2["CNT"] = df$CNT
df_pca = df2
head(df_pca)
#now CNT is the last one purtroppo

pca = princomp(df_pca[,1:dim(df_pca)[2]-1])
summary(pca)

###############################################################################
plot(cumsum(pca$sde^2)/sum(pca$sde^2), type='b', axes=F, xlab='Number of components',
     ylab='Contribution to the total variance', ylim=c(0,1),
     main=paste("Case of",cat_curr_name))
abline(h=1, col='blue')
abline(h=0.8, lty=2, col='blue')
box()
axis(2,at=0:10/10,labels=0:10/10)
axis(1,at=1:ncol(df_pca),labels=1:ncol(df_pca),las=2)

print("loadings plot")
sort(pca$loadings[,1]) #test soglia
quantile(pca$loadings[,1],0.8) #test soglia
mean(pca$loadings[,1]) #test soglia
median(pca$loadings[,1]) #test soglia

###############################################################################
par(mfrow=c(2,1))
for(i in 1:2){
  # soglia = quantile(pca$loadings[,i],0.6)),i]
  soglia = 0
  barplot(
      # pca$loadings[which(abs(pca$loadings[,i])>0.02),i],
      # pca$loadings[which(abs(pca$loadings[,i])>soglia)],
      pca$loadings[,i],
      main=paste('Loadings PC',i),las=2
      )
      # pca$loadings[which(abs(pca$loadings[,i])>mean(pca$loadings[,i]))])
}

###############################################################################
# higher pcs
# par(mar = c(2,2,2,1), mfrow=c(3,1))
# for(i in 3:5)barplot(pca$loadings[,i], ylim = c(-1, 1),
# main=paste('Loadings PC ',i,sep=''),las=2)
```

### Interpretation
```{r}
for (col in cat_curr_vec){
  print(paste(col,what_is[[col]]))
}
# arriva
```

### Scores plot
```{r}
i=0
for (x in unique(df$CNT)) {
  # print(x)
  if (i%%2==0) { par(mfrow=c(1,2))  }
  i=i+1
  plot(pca$scores[which(df$CNT==x),1:2],main = paste0(toupper(cat_curr_name),": ",x))
       # xlab = paste(cat_curr_name,"Comp.1"),ylab = paste(cat_curr_name,"Comp.2"))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}

```












```{r}
for (x in unique(df$CNT)[1:4]) {
  # print(x)
  plot(pca$scores[which(df$CNT==x),1:2],main = paste(x))
  abline(h=0, v=0, lty=2, col='grey')
  points(0,0,pch=19,cex=1.4,col="orange")
}
```

