---
title: "Factor Analysis"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

# NOTES AND REFERENCES

-   Exploratory Factor Analysis (EFA) tutorial: <https://rpubs.com/pjmurphy/758265>

-   source: <https://www.geo.fu-berlin.de/en/v/soga/Geodata-analysis/factor-analysis/A-simple-example-of-FA/index.htmlZ>

# PRELIMINARY STUFF

```{r}
library(dplyr)
library(psych) #for KMO test
```

```{r, setup}
#DIRECTORIES
root_proj_dir = "../../"
dataset_dir = paste(root_proj_dir,"/data/pisa-woNA_school_final.csv",sep="")
include_dir = paste(root_proj_dir,"/src/include/Utilities.R",sep="")
#INCLUDING UTILITIES
source(include_dir)
#IMPORTING THE DATASET
pisa_data <- read.csv(file=dataset_dir)
```

```{r}
#some adjustments on the data
pisa_data$X <- NULL
pisa_data$schID <- NULL
pisa_data$CNT <- as.factor(pisa_data$CNT)
```

```{r}
#variabili finite nel dataset
included_variables <-list()
#list of grouped variables
included_variables[["tec"]] <- c("ICTCLASS","ICTHOME","ICTOUTSIDE","ICTRES","AUTICT","COMPICT","INTICT","ENTUSE","HOMESCH","USESCH")
included_variables[["psi"]] <- c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","GFOFAIL","SWBP","RESILIENCE","BELONG","BEINGBULLIED","PERFEED")
included_variables[["clt"]] <- c("JOYREAD","CULTPOSS","HEDRES","SCREADCOMP","LMINS","MMINS")
included_variables[["fam"]] <- c("WEALTH","ESCS","HOMEPOS","BFMJ2","BMMJ1","HISCED","HISEI")
included_variables[["tch"]] <- c("TEACHINT","TEACHSUP","STIMREAD")
included_variables[["sch"]] <- c("PERCOMP","PERCOOP","ICTSCH","RATCMP1")
```

# LOOKING FOR HIGH CORRELATION

```{r}
KMO(select_if(pisa_data,is.numeric))
#values are good
cortest.bartlett(select_if(pisa_data,is.numeric))
```

# PERFORMING EFA

```{r}
ev <- eigen(cor(select_if(pisa_data,is.numeric))) # get eigenvalues
ev$values
#plotting eigenvalues
scree(select_if(pisa_data,is.numeric), pc=FALSE)
fa.parallel(select_if(pisa_data,is.numeric), fa="fa")
```

```{r}
n = dim(pisa_data)[1]
p = dim(pisa_data)[2]
#all toghether
pisa.fa <- factanal(select_if(pisa_data,is.numeric), factors = 10, rotation = "varimax")
pisa.fa
pisa.pca <-princomp(pisa_data[,4:p])
pisa.fa$loadings
pisa.load = pisa.pca$loadings

x11()
par(mfcol=c(3,1))
for(i in 1:2) barplot(pisa.load[,i] ,las=2,ylim = c(-1, 1), main=paste("PC Loadings",i))
x11()
par(mfcol=c(3,1))
for(i in 3:4:5) barplot(pisa.load[,i] ,las=2,ylim = c(-1, 1), main=paste("PC Loadings",i))
```

# analisi sospetti

```{r}
# i factor più importanti sembrano mmins e lmins, perché?
colnames(pisa_data)
x11()
boxplot(pisa_data[,5:44], las=2, main="pisa cols")
# forse le prende perché hanno alta varianza?


```

```{r}
#fam,2
#tec,5
#tch,1
var = tch
factors= 2
pisa.fa <- factanal(pisa_data[,var], factors = factors,rotation = "varimax")
pisa.fa

pisa.load = pisa.pca$loadings

x11()
par(mfcol=c(5,1))
for(i in 1:5) barplot(pisa.load[,i] ,las=2,ylim = c(-1, 1), main=paste("PC Loadings",i))
plot(pisa.fa$loadings[,1], 
     pisa.fa$loadings[,2],
     xlab = "Factor 1", 
     ylab = "Factor 2",
     ylim = c(-1,1),
     xlim = c(-1,1),
     main = "Promax rotation")
abline(h = 0, v = 0)
```
