---
output: html_document
editor_options: 
  chunk_output_type: inline
---
# Data generation

## Settings

```{r}
#directories
working_dir = "C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/progetto-applied/data"
complete_data_dir =  "C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/Dataset_PISA/SPSS FORMAT"
```

Selected variables and countries according to `selected_variables.txt`

```{r}
#countries
selected_countries = c("HRV","CZE","DNK","EST","FIN","FRA","GRC","HUN","IRL","LTU","LUX","POL","SVK","SVN","ESP","SWE")

#Gender
stu_GENDER = c("ST004D01T")
#Technology
stu_ICT = c("ICTCLASS","ICTHOME","ICTOUTSIDE","ICTRES","AUTICT","COMPICT","INTICT","ENTUSE","HOMESCH","USESCH")
sch_ICT = c("RATCMP1")
#Family
stu_FAM = c("WEALTH","ESCS","HOMEPOS","BFMJ2","BMMJ1","HISCED","HISEI")
#Culture
stu_CULT = c("JOYREAD","CULTPOSS","HEDRES","SCREADCOMP","LMINS","MMINS")
#Well-being
stu_WB = c("ATTLNACT","EMOSUPS","COMPETE","EUDMO","GFOFAIL","SWBP","RESILIENCE","BELONG","BEINGBULLIED","PERFEED")
#Professori
stu_PROF = c("TEACHINT","TEACHSUP","STIMREAD")
#School
stu_SCH = c("PERCOMP","PERCOOP","ICTSCH")

#all together
stu_vars = c(stu_GENDER,stu_ICT,stu_FAM,stu_CULT,stu_WB,stu_PROF,stu_SCH)
sch_vars = c(sch_ICT)
all_vars <-c(stu_vars,sch_vars)
teach_vars = c()
```

Data loading

```{r}
library(intsvy)

pisa_data <- pisa.select.merge(folder= complete_data_dir,
                               school.file="CY07_MSU_SCH_QQQ.sav", 
                               student.file="CY07_MSU_STU_QQQ.sav",
                               student= stu_vars,
                               school = sch_vars,
                               countries = selected_countries)    
```
# add SCHLTYPE
```{r}
dataset_path="C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/Dataset_PISA/SPSS FORMAT"
pisa_data_schtype <- pisa.select.merge(folder= dataset_path,
                               school.file="CY07_MSU_SCH_QQQ.sav",
                                student.file="CY07_MSU_STU_QQQ.sav",
                               school = c("SCHLTYPE","PRIVATESCH","SC013Q01TA")	,
                               countries = selected_countries)   

head(pisa_data_schtype)
unique(pisa_data_schtype$SCHLTYPE)
unique(pisa_data_schtype$PRIVATESCH)
unique(pisa_data_schtype$SC013Q01TA)
```

```{r}
#decode the variable SCHLTYPE
pisa_data_schtype$SCHLTYPE <- as.factor(pisa_data_schtype$SCHLTYPE)
pisa_data_schtype <- pisa_data_schtype %>%
  mutate(SCHLTYPE = case_when(
    SCHLTYPE == "1" ~ "Private Independent",
    SCHLTYPE == "2" ~ "Private Government-dependent",
    SCHLTYPE == "3" ~ "Public",
    TRUE ~ NA_character_
  ))
```

```{r}
pisa_data_schtype$SCHLTYPE <- as.factor(pisa_data_schtype$SCHLTYPE)
plot(pisa_data_schtype$SCHLTYPE)
length(pisa_data_schtype[pisa_data_schtype$SCHLTYPE!="Public",1])

#troppi NA
pisa_data_schtype$PRIVATESCH <- as.factor(pisa_data_schtype$PRIVATESCH)
plot(pisa_data_schtype$PRIVATESCH)
length(pisa_data_schtype[pisa_data_schtype$PRIVATESCH!="public ",1])

pisa_data_schtype$SC013Q01TA <- as.factor(pisa_data_schtype$SC013Q01TA)
plot(pisa_data_schtype$SC013Q01TA)
length(pisa_data_schtype[pisa_data_schtype$SC013Q01TA=="2",1])

```

```{r}
getwd()
dataset_dir = "C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/progetto-applied/data/"
pisa_data <- read.csv(file=paste(dataset_dir,"pisa_wPV_grouped_bysch_schtype.csv",sep=""))
head(pisa_data)
pisa_data$X<-NULL
pisa_data$CNTSCHID<-NULL
pisa_data$CNTSTUID<-NULL

write.csv(pisa_data,"C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/progetto-applied/data/pisa_data_final.csv")
```


# 

```{r}
library(dplyr)

pisa_data <- pisa_data %>% select(-starts_with("W_FSTU")) 
pisa_data <- pisa_data %>% select(-starts_with("PV"))
pisa_data <- pisa_data %>% select(-c("CNTRYID","CNTSTUID","BOOKID")) 
```

# NA treatment

```{r}
library(dplyr)
library(tidyr)

pisa_data_woNA <- pisa_data %>% group_by(CNT) %>% mutate_if(is.numeric, ~replace_na(.,median(., na.rm = TRUE)))
```

## Saving data

```{r}
library(utils)
saving_dir = paste(working_dir,"/pisa-woNA_school.csv",sep="")
write.csv(pisa_data_woNA,file=saving_dir)
```

# Grouping by school

```{r}
setwd("C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/progetto-applied/data")
pisa_by_sch <- read.csv("pisa-woNA_school.csv")
colnames(pisa_by_sch)
```

TO BE FIXED

```{r}
pisa_by_school <-aggregate(x = pisa_by_sch, by= list(pisa_by_sch$CNTSCHID,pisa_by_sch$CNT), FUN=mean)
```

```{r}
dim(pisa_by_school)
colnames(pisa_by_school)
head(pisa_by_school)
pisa_by_school[stu_GENDER]
```

```{r}
pisa_by_school <- pisa_by_school %>% select(-starts_with("CNT")) 
pisa_by_school <- pisa_by_school %>% select(-starts_with("x")) 
pisa_by_school_final <- pisa_by_school
colnames(pisa_by_school_final)[c(1,2,3)]<-c("schID","CNT","gender_prop")
colnames(pisa_by_school_final)

```

```{r}
saving_dir = paste(working_dir,"/pisa-woNA_school_final.csv",sep="")
write.csv(pisa_by_school_final,file=saving_dir)
```
