---
title: 'One-way MANOVA'
output: 
editor_options: 
  chunk_output_type: inline
---

# PRELIMINARY STUFF

```{r}
#directories
working_dir ="C:/Users/modin/Desktop/Ettore/UNIVERSITA/PISA_PROJECT/progetto-applied"
dataset_dir = "../data"
include_dir = paste(working_dir,"/src/include/Utilities.R",sep="")
#including utilities
#including utilities
source(include_dir)
#importing the dataset
pisa_data <- read.csv(file=paste(working_dir,"/data/pisa-woNA_school_final.csv",sep=""))
data<-pisa_data
dim(data)
colnames(data)
library(MVN)
library(car)
library(heplots)
library(mvnormtest)
```

```{r}
#select only ICT moments fot the moment
library(dplyr)
data <- data %>% dplyr::select(all_of(c("CNT",stu_PROF)))
```

# **1.** Data
```{r, warning=FALSE, message=FALSE}
# what column identify the group?
lab_index <- 1
p = dim(data)[2] 
p
v = c()

# Re-name
colnames(data)[lab_index]="label"
head(data)

cols <- seq(1,p)
feats <- cols[!cols %in% lab_index]

data.feats = data[,feats]
data$label<-as.factor(data$label)

p     = length(feats) #don't count the column of labels

```

# **2.** Exploration
```{r, warning=FALSE, message=FALSE}

# Dimensions
n     = length(data$label) # total number of obs.
ng    = table(data$label)  # number of obs. in each group
treat_factors <- factor(data$label)
treat = levels(treat_factors) # levels of the treatment
g     = length(treat)      # number of levels (i.e., of groups)

indeces = list()
for (jj in 1:g){
    indeces[jj] <- list(which(data$label == treat[jj]))
}
n_list = list()
for(j in 1:g) {
  n_list[j] = list(length(indeces[[j]]))
}
n=0
for(j in 1:g) {
  n = n +  n_list[[j]]
}
# Plot: different panels -> different group
x11()
par(mfrow=c(2,g/4))
for (j in 1:(g/2)){
  boxplot(data.feats[as.numeric(indeces[[j]]),], main=paste('group ',j),  ylim=c(round(min(data.feats)),
          round(max(data.feats))), col = rainbow(g)[j])
}
x11()
par(mfrow=c(4,g/8))
for (j in (g/2+1):g){
  boxplot(data.feats[as.numeric(indeces[[j]]),], main=paste('group ',j),  ylim=c(round(min(data.feats)),
          round(max(data.feats))), col = rainbow(g)[j])
}

## Plot: different panels -> different feature

for (j in 1:p){
  boxplot(data.feats[,j]~data$label, main=paste('X',j), col = rainbow(p)[j])
}

```

# **ONE-WAY MANOVA** 

## Checking the assumptions 

lol

## Fitting the model

One-way it's the only thing that makes sense in our situation

```{r}
fit = manova(as.matrix(data.feats) ~ data$label)
summary.manova(fit, test="Wilks")
Ps_mvn <- NULL
for(j in 1:g) {
  mvn.test <- mvn(data = data[indeces[[j]] , feats])
  Ps_mvn <- c(Ps_mvn, mvn.test$multivariateNormality$`p value`)
}
Ps_mvn


# 2. same covariance structure (homoschedasticity)
S  = cov(data.feats)
Slist = list()
for (j in 1:g){
  Slist[j] = list(cov(data.feats[indeces[[j]],]))
  # Qualitatively:
  round(Slist[[j]],digits=1)
}
summary(boxM(data.feats, treat_factors))

temp <- do.call(rbind, Slist)
for (j in 1:g){
  image(Slist[[j]], col=heat.colors(100),main=paste('Cov. S',j), asp=1, axes = FALSE,
      breaks = quantile(temp, (0:100)/100, na.rm=TRUE))
}
```
ì
# **5.** Which supplement is responsible?
(In the case we accept H1)
```{r, warning=FALSE, message=FALSE}
# First of all:
#   Let's see on which variables the group has an effect.
#   Via ANOVA: for each feature we perform an ANOVA to see if the belonging to
#   the group has an effect on the mean of the variables.
summary.aov(fit,test="Wilks")

# Comment
# Pr(>F) = p-value small -> the group has an influence on that X_k
# This analysis does NOT say either which groups differ nor which are the variables
# for which the groups differ.
```


## **6.**Bonferroni CI: CHOOSE ALPHA

We want to know the level (of the labels) that introduces the difference.
We have to create g*(g-1)/2 intervals.
```{r, warning=FALSE, message=FALSE}
alpha = 0.0001
k     = p*g*(g-1)/2
qT    = qt(1-alpha/(2*k), n-g)

W1 <- diag(t(fit$res) %*% fit$res) # fit$re^2 
SSres <- sum(W1)
var = SSres/(n-g)
W     = summary.manova(fit)$SS$Residuals
SSres == sum(diag(W))

m  = sapply(data.feats,mean)      # estimates mu

m_list = list()
for (j in 1:g){
  m_list[j] = list(sapply(data.feats[indeces[[j]],],mean)) # estimates mu.1=mu+tau.j
}
mg <- do.call(rbind, m_list)
mg

inf_list = list()
sup_list = list()
mean_list = list()
## be careful, order could be reversed 

for(i in 1:(g-1)) {
  for(j in (i+1):g) {
    ind <- (i-1)*g-i*(i-1)/2+(j-i)
    inf_list[ind] <- list(m_list[[i]]- m_list[[j]] - qT * sqrt( diag(W)/(n-g)
                                                                *(1/n_list[[i]]+1/n_list[[j]])))
    mean_list[ind]<-list(m_list[[i]]- m_list[[j]])
    sup_list[ind] <- list(m_list[[i]]- m_list[[j]] + qT * sqrt( diag(W)/(n-g)
                                                                *(1/n_list[[i]]+1/n_list[[j]])))
  }
}

CI = list()
for(i in 1:ind){
  CI[i] <- list(cbind(inf = inf_list[[i]],mean = mean_list[[i]], sup = sup_list[[i]]))
}

names_CI<-c()
for(i in 1:(g-1)) {
  for(j in (i+1):g) {
    names_CI<-c(names_CI,paste(treat[i],treat[j]))

  }
}
names(CI)<-names_CI
```


```{r, warning=FALSE, message=FALSE}
# Now we have a complete frame (intervals for all the components of tau_i)

# Comment
#   From these intervals we can see who is responsable for the change:
#   if the zero is NOT present in a comparison 'gi_gj' in an interval 'Xk'
#   then the variable 'Xk' is influenced by groups 'gi' and 'gj'.

# Plot: different panels -> different features



### cambia nome titolo
for(k in 1:p){
  #x11()
  #par(mfrow=c(2,1))
   # Order boxes by median
  group_ordered <- with(data,
                        reorder(data$label,data.feats[,k],mean))
  
  boxplot(data.feats[,k]~group_ordered, main=paste(colnames(data.feats)[k]),las=2,
        ylim=c(round(min(data.feats[,k])),
        round(max(data.feats[,k]))), col = rainbow(g))
  abline(h=0)
  plot(c(1,5), xlim=c(c(1,5)), pch='',ylim=c(min(unlist(CI)),max(unlist(CI))),
     xlab='pairs treat', ylab=paste('CI tau',colnames(data.feats)[k]),
     main=paste('CItau',colnames(data.feats)[k]))
    abline(h=0)
    ######
    i=1
    j=2
    h=1
    while(i!=g&&j!=g-1){
      print(c(i,j))
      temp <- sort(c(levels(group_ordered)[i],levels(group_ordered)[j]))
      ind<-paste(temp[1],temp[2])
      if(CI[[ind]][k,1]*CI[[ind]][k,3]<0){ # zero in the interval
        j=j+1 
      }
      else{
        print( names(CI[ind]))
        lines (c(h,h), c(CI[[ind]][k,1],CI[[ind]][k,3])); 
        #points(ind, mg[ii,k]-mg[jj,k], pch=16); 
        points(h, CI[[ind]][k,1], col=rainbow(g)[j], pch=16); 
        points(h, CI[[ind]][k,2], col="black", pch=16); 
        points(h, CI[[ind]][k,3], col=rainbow(g)[i], pch=16); 
        i=j
        j=i+1
        h=h+1
      }
    }
    print("####")

}
      
# Comment
#   If no one contains 0 it means that every group has relevance in every feature.
```


