---
title: "R Notebook"
#output: html_notebook
editor_options: 
  chunk_output_type: inline
---
```{r}
library(dplyr)
```

```{r}
linear_model_vars <- readLines( "../../data/non csv/lm_social_vars.txt")

filter <- function(category,var_lm) {
  risultato <- c()
  
  for (elemento in category) {
    if (elemento %in% var_lm) {
      risultato <- c(risultato, elemento)
    }
  }
  
  return(risultato)
}


categories_variables_filtered=list()

for(cat in cat_var_names ){
  categories_variables_filtered[[cat]]=filter(categories_variables[[cat]],linear_model_vars)
}

categories_variables_filtered
```


```{r}
# Perform analysis of variance
anova_result <- anova(fit)

# Extract sums of squares and total sum of squares
ss_total <- sum(anova_result$'Sum Sq')
ss_covariates <- anova_result$'Sum Sq'[-length(anova_result$'Sum Sq')]

# Calculate proportion of explained variance for each covariate
explained_variance <- (ss_covariates / ss_total)*100
var_df <- data.frame(Covariate = names(coefficients(fit))[1:length(explained_variance)], explained_Variance = explained_variance)
var_df$group_var = rep("INTERCEPT",12)
k=1
for(group in categories_variables_filtered){
  for(var in group){
    var_df[var_df$Covariate==var,3]=names(categories_variables_filtered)[k]
  }
  k=k+1
}

```


```{r}
# Calculate the total explained variance for each group
group_explained_variance <- aggregate(explained_Variance ~ group_var, var_df, sum)

# Order the groups by explained variance in reverse order
group_explained_variance <- group_explained_variance[order(group_explained_variance$explained_Variance, decreasing = TRUE), ]
var_df$group_var <- factor(var_df$group_var, levels = rev(group_explained_variance$group_var))

# Plot the bar chart with explained variance labels
plot <- ggplot(data = var_df, aes(x = 1, y = explained_Variance, fill = group_var)) +
  geom_bar(stat = "identity", width = 0.5) +
  ylim(0, 100) +
  scale_fill_viridis_d() +
  theme_bw() +
  theme(
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.title.x = element_blank(),
    legend.title = element_blank(),
    legend.position = "right",
    legend.spacing = unit(0.2, "cm"),
    legend.text = element_text(size = 10)
  ) +
   geom_text(data = group_explained_variance, aes(label = round(explained_Variance, 2)), position = position_stack(vjust = 0.5), size = 4)

svg("prop_explained.svg")
plot

dev.off()
```

```{r}
pdf("explained variability.pdf")
print(plot)
dev.off()
```

